language: csharp
mono: none
dotnet: 1.0.0-preview2-1-003177
solution: GovITHub.Auth.Identity.sln
dist: trusty
sudo: required

before_script:
    - npm install -g bower --prefix ./src
    - npm install -g gulp --prefix ./src
    - npm install --prefix ./src

script:
    - dotnet restore
    - dotnet build src/GovITHub.Auth.Common
    - dotnet build src/GovITHub.Auth.Identity
    - dotnet build src/GovITHub.Auth.Admin
    - dotnet test test/GovITHub.Auth.Common.Tests -c Release -f netcoreapp1.0